wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704488984.231382
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
